---
- hosts: localhost
  connection: local
  vars_files:
    - ec2_instances.yml   # Variable file for EC2 instances
    - secrets.yaml        # Encrypted secrets file

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "all"
        instance_type: t2.micro
        security_group: default
        region: ap-south-1
        aws_access_key: "{{ ec2_access_key }}"  # From encrypted secrets file
        aws_secret_key: "{{ ec2_secret_key }}"  # From encrypted secrets file      
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
      loop: "{{ ec2_info }}"  # Use the variable defined in the file
